import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(const MinhaApp());

class Item { final String name; final int price; int qty; Item(this.name,this.price,{this.qty=1}); int get total=>price*qty; }

class MinhaApp extends StatelessWidget {
  const MinhaApp({super.key});
  @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Minha Food Delivery',theme:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFF087A3B)),useMaterial3:true),home:const Home());
}

class Home extends StatefulWidget { const Home({super.key}); @override State<Home> createState()=>_HomeState(); }
class _HomeState extends State<Home> {
  int tab=0; final cart=<Item>[];
  final cats=<String>['🍔 Food','🛒 Grocery','🥬 سبزی','💊 Medicine','📦 Other'];
  final products=<Item>[Item('Chicken Biryani',280),Item('Chicken Pizza',650),Item('Burger',250),Item('Fresh Vegetables',120)];
  int get subtotal=>cart.fold(0,(s,x)=>s+x.total); int get total=>cart.isEmpty?0:subtotal+100;
  void add(String n,int p){setState((){final i=cart.indexWhere((x)=>x.name==n);if(i>=0)cart[i].qty++;else cart.add(Item(n,p));});}
  Future<void> orderWhatsApp() async { if(cart.isEmpty)return; final lines=cart.map((x)=>'${x.name} x${x.qty} = Rs. ${x.total}').join('\n'); final msg='Assalam-o-Alaikum Minha Food Delivery,\nNew Order:\n$lines\nSubtotal: Rs. $subtotal\nDelivery Charges: Rs. 100\nTotal: Rs. $total\nPayment: Cash on Delivery\nArea: Mian Channu\nName:\nPhone:\nAddress:'; final u=Uri.parse('https://wa.me/923336245021?text=${Uri.encodeComponent(msg)}'); await launchUrl(u,mode:LaunchMode.externalApplication); }
  @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(backgroundColor:const Color(0xFF087A3B),foregroundColor:Colors.white,title:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Minha Food Delivery',style:TextStyle(fontWeight:FontWeight.bold)),Text('Mian Channu',style:TextStyle(fontSize:12))]),actions:[IconButton(onPressed:cartSheet,icon:Badge(isLabelVisible:cart.isNotEmpty,label:Text('${cart.length}'),child:const Icon(Icons.shopping_cart_outlined)))]),body:tab==0?home():tab==1?categories():tab==2?orders():profile(),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),label:'Home'),NavigationDestination(icon:Icon(Icons.grid_view),label:'Categories'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),label:'Orders'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Profile')]));
  Widget home()=>ListView(padding:const EdgeInsets.all(16),children:[TextField(decoration:InputDecoration(hintText:'Search food, grocery, medicine...',prefixIcon:const Icon(Icons.search),border:OutlineInputBorder(borderRadius:BorderRadius.circular(14)))),const SizedBox(height:16),Container(height:190,decoration:BoxDecoration(borderRadius:BorderRadius.circular(18),gradient:const LinearGradient(colors:[Color(0xFF087A3B),Color(0xFF16A05A)])),child:const Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.delivery_dining,color:Colors.white,size:70),Text('Minha Food Delivery',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.bold)),Text('Mian Channu',style:TextStyle(color:Colors.white,fontSize:18))]))),const SizedBox(height:14),Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFFE8F6ED),borderRadius:BorderRadius.circular(16)),child:const Text('📍 صرف میاں چنوں میں  •  🛵 Delivery Rs. 100  •  💵 Cash on Delivery',style:TextStyle(fontWeight:FontWeight.w700))),const SizedBox(height:18),const Text('Categories',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:8),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:5,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,crossAxisSpacing:8,mainAxisSpacing:8),itemBuilder:(_,i)=>Card(child:Center(child:Text(cats[i],textAlign:TextAlign.center)))),const SizedBox(height:18),const Text('Popular Items',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...products.map((p)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.restaurant)),title:Text(p.name),subtitle:Text('Rs. ${p.price}'),trailing:FilledButton(onPressed:()=>add(p.name,p.price),child:const Text('Add'))))) ]);
  Widget categories()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Choose a category',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),...cats.map((x)=>Card(child:ListTile(title:Text(x),trailing:const Icon(Icons.chevron_right))))]);
  Widget orders()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('My Orders',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const Card(child:ListTile(leading:Icon(Icons.delivery_dining),title:Text('No orders yet'),subtitle:Text('Your orders will appear here.')))]);
  Widget profile()=>ListView(padding:const EdgeInsets.all(16),children:[const CircleAvatar(radius:42,child:Icon(Icons.person,size:48)),const SizedBox(height:10),const Center(child:Text('Customer',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold))),const SizedBox(height:16),...['My Orders','Saved Addresses','Help & Support','Settings'].map((x)=>Card(child:ListTile(title:Text(x),trailing:const Icon(Icons.chevron_right))))]);
  void cartSheet()=>showModalBottomSheet(context:context,isScrollControlled:true,builder:(ctx)=>StatefulBuilder(builder:(ctx,refresh)=>Padding(padding:const EdgeInsets.fromLTRB(16,16,16,30),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('My Cart',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),if(cart.isEmpty)const Padding(padding:EdgeInsets.all(25),child:Text('Cart خالی ہے')), ...cart.map((x)=>ListTile(title:Text(x.name),subtitle:Text('Rs. ${x.price} × ${x.qty}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:(){setState(()=>x.qty>1?x.qty--:cart.remove(x));refresh((){});},icon:const Icon(Icons.remove_circle_outline)),Text('${x.qty}'),IconButton(onPressed:(){setState(()=>x.qty++);refresh((){});},icon:const Icon(Icons.add_circle_outline))]))),if(cart.isNotEmpty)...[const Divider(),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Subtotal'),Text('Rs. $subtotal')]),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Delivery'),const Text('Rs. 100')]),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Total',style:TextStyle(fontWeight:FontWeight.bold,fontSize:18)),Text('Rs. $total',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:18))]),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:orderWhatsApp,icon:const Icon(Icons.chat),label:const Text('Order on WhatsApp')))] ]))));
}
